{
    'name': 'Guatemala - reportes y funcionalidad extra',
    'version': '6.10',
    'category': 'Accounting/Localizations/Reporting',
    'description': """ Reportes requeridos por la SAT y otra funcionalidad extra para llevar un contabilidad en Guatemala. """,
    'author': 'aquíH',
    'website': 'http://www.aquih.com/',
    'depends': ['l10n_gt', 'account_tax_python', 'product'],
    'data': [
        'views/account_views.xml',
        'views/res_partner_views.xml',
        'views/res_company_views.xml',
        'views/product_views.xml',

        'report/report_views.xml',
        'report/reporte_banco_views.xml',
        'report/reporte_partida_views.xml',
        'report/reporte_compras_views.xml',
        'report/reporte_ventas_views.xml',
        'report/reporte_inventario_views.xml',
        'report/reporte_diario_views.xml',
        'report/reporte_mayor_views.xml',

        'wizard/account_account_reporte_banco_views.xml',
        'wizard/account_journal_reporte_compras_views.xml',
        'wizard/account_account_reporte_diario_views.xml',
        'wizard/account_account_reporte_inventario_views.xml',
        'wizard/account_account_reporte_mayor_views.xml',
        'wizard/account_journal_reporte_ventas_views.xml',

        'security/ir.model.access.csv',
    ],
    'demo': [],
    'installable': True,
    'license': 'Other OSI approved licence',
    'post_init_hook': '_update_gt_taxes',
}